// vo3d app — THE DELIVERED RESULT, inspectable (AI-workforce demo, `?ailab=v2&aidemo=1`).
//
// Renders ONE ArtifactResult (world/agentOrchestration) — whatever produced it. Nothing about the job is written
// here: the title, the stages, the checks and the miniature page all come from the payload, so a real Agent
// Harness artifact replaces the mock one without this component changing. The payload's `source` is always
// shown: a mock result never reads as real execution.
//
// Deliberately light: a preview card, not a browser, editor or artifact platform. Approve / Request Changes and
// the conversation about the result are Phase 5.
import { useEffect, type CSSProperties } from "react";
import type { ArtifactResult, LandingPageDeliverable } from "../world/agentOrchestration";
import styles from "./AiLabResultPreview.module.css";

export function AiLabResultPreview({ result, onClose }: { result: ArtifactResult; onClose: () => void }) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);
  return (
    <div className={styles.backdrop} onClick={onClose} data-testid="ailab-result-preview">
      <div className={styles.card} role="dialog" aria-modal="true" aria-label={`Result: ${result.title}`} onClick={(e) => e.stopPropagation()}>
        <header className={styles.head}>
          <div>
            <div className={styles.kicker}>
              <span className={styles.badge}>Result ready</span>
              {result.source === "mock" && <span className={styles.mockBadge}>Mock demo result</span>}
            </div>
            <h2 className={styles.title}>{result.title}</h2>
            <p className={styles.summary}>{result.summary}</p>
          </div>
          <button type="button" className={styles.close} onClick={onClose} aria-label="Close result">×</button>
        </header>
        <div className={styles.body}>
          {result.deliverable.kind === "landing-page" && <LandingPageMini page={result.deliverable} />}
          <aside className={styles.side}>
            <h3 className={styles.sideTitle}>How it was made</h3>
            <ol className={styles.stages}>
              {result.stages.map((s) => (
                <li key={s.role} className={styles.stage}>
                  <span className={styles.tick} aria-hidden="true">✓</span>
                  <div>
                    <div className={styles.stageHead}><b>{s.role}</b> {s.outcome === "passed" ? "passed" : "completed"}<span className={styles.by}>{s.by}</span></div>
                    <div className={styles.note}>{s.note}</div>
                  </div>
                </li>
              ))}
            </ol>
            {result.deliverable.kind === "landing-page" && result.deliverable.checks.length > 0 && (
              <>
                <h3 className={styles.sideTitle}>Review checks</h3>
                <ul className={styles.checks}>
                  {result.deliverable.checks.map((c) => <li key={c}><span className={styles.dotOk} aria-hidden="true" />{c}</li>)}
                </ul>
              </>
            )}
            <p className={styles.footnote}>
              {result.source === "mock"
                ? "Produced by the demo's scripted orchestration — not generated by Agent Harness."
                : "Produced by Agent Harness."}
              {" "}Requested by {result.requestedBy}.
            </p>
          </aside>
        </div>
      </div>
    </div>
  );
}

/** THE DELIVERABLE, MINIATURE: a landing page drawn from its own data (palette, copy, sections) */
function LandingPageMini({ page }: { page: LandingPageDeliverable }) {
  const p = page.palette;
  const vars = { "--lp-bg": p.bg, "--lp-surface": p.surface, "--lp-ink": p.ink, "--lp-muted": p.muted, "--lp-accent": p.accent, "--lp-accent-ink": p.accentInk } as CSSProperties;
  return (
    <figure className={styles.frame} style={vars} aria-label={`${page.brand} landing page preview`}>
      <div className={styles.chrome} aria-hidden="true">
        <span /><span /><span />
        <div className={styles.url}>{page.brand.toLowerCase()}.com</div>
      </div>
      <div className={styles.page}>
        <nav className={styles.nav}>
          <b className={styles.brand}><i className={styles.logo} />{page.brand}</b>
          <span className={styles.links}>{page.nav.map((n) => <span key={n}>{n}</span>)}</span>
          <span className={styles.navCta}>{page.hero.primaryCta}</span>
        </nav>
        <section className={styles.hero}>
          <div className={styles.heroCopy}>
            <span className={styles.eyebrow}>{page.hero.eyebrow}</span>
            <h4 className={styles.headline}>{page.hero.headline}</h4>
            <p className={styles.subhead}>{page.hero.subhead}</p>
            <div className={styles.ctas}>
              <span className={styles.cta}>{page.hero.primaryCta}</span>
              <span className={styles.ghost}>{page.hero.secondaryCta}</span>
            </div>
          </div>
          <div className={styles.art} aria-hidden="true">
            <div className={styles.artCard}><i /><i /><i /></div>
            <div className={`${styles.artCard} ${styles.artCard2}`}><i /><i /></div>
            <div className={styles.artCircle} />
          </div>
        </section>
        <section className={styles.features}>
          {page.features.map((f) => (
            <div key={f.title} className={styles.feature}>
              <i className={styles.featureIcon} aria-hidden="true" />
              <b>{f.title}</b>
              <span>{f.body}</span>
            </div>
          ))}
        </section>
        <div className={styles.proof}>{page.proof}</div>
      </div>
    </figure>
  );
}
