"""add chat read receipts and dm key

Revision ID: 0cda7ceb4522
Revises: b6662cbdb011
Create Date: 2026-08-14 12:50:02.466697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cda7ceb4522'
down_revision: Union[str, Sequence[str], None] = 'b6662cbdb011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dm_key', sa.String(length=600), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_dm_key'), ['dm_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_dm_key'))
        batch_op.drop_column('dm_key')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_column('last_read_at')

    # ### end Alembic commands ###
