"""add_meeting_intelligence

Phase 7A — Meeting Intelligence Foundation. The durable, provider-neutral data layer for AI-generated
meeting intelligence, owned by the Meeting Session and grounded in its transcript segments. No AI provider,
no content is generated by this migration.

THREE ADDITIVE VO TABLES, NOTHING ELSE TOUCHED (no Atlas table, no existing VO table altered):

  meeting_intelligence_runs      one versioned generation over one meeting session: status, generator id,
                                 requester, UTC start/finish, failure code, and the transcript snapshot it
                                 analyzed (segment ids + fingerprint + boundary).

  meeting_intelligence_items     structured outputs of a run (summary/topic/decision/commitment/open_loop/
                                 key_point): immutable generated content, confidence, uncertainty, and the
                                 human review state beside it (suggested/confirmed/edited/rejected).

  meeting_intelligence_evidence  item → transcript_segments citations by id.

Foreign keys point only at meeting_sessions, transcript_segments (Phases 6A/6B) and these tables. Starts empty.

Revision ID: c5d6e7f8a9b1
Revises: b4c5d6e7f8a0
Create Date: 2026-09-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d6e7f8a9b1'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "meeting_intelligence_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meeting_session_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("generator", sa.String(length=64), nullable=False),
        sa.Column("requested_by_email", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=32), nullable=True),
        sa.Column("source_segment_ids", sa.JSON(), nullable=False),
        sa.Column("source_segment_count", sa.Integer(), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_through_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["meeting_session_id"], ["meeting_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_session_id", "version", name="uq_meeting_intelligence_run_version"),
    )
    op.create_index(
        op.f("ix_meeting_intelligence_runs_meeting_session_id"),
        "meeting_intelligence_runs",
        ["meeting_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_meeting_intelligence_runs_session_status",
        "meeting_intelligence_runs",
        ["meeting_session_id", "status"],
        unique=False,
    )

    op.create_table(
        "meeting_intelligence_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("item_type", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=16), server_default="generated", nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("uncertainty", sa.Text(), nullable=True),
        sa.Column("review_state", sa.String(length=16), server_default="suggested", nullable=False),
        sa.Column("reviewed_content", sa.JSON(), nullable=True),
        sa.Column("reviewed_by_email", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["run_id"], ["meeting_intelligence_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_intelligence_items_run_id"), "meeting_intelligence_items", ["run_id"], unique=False
    )
    op.create_index(
        "ix_meeting_intelligence_items_run_position", "meeting_intelligence_items", ["run_id", "position"], unique=False
    )

    op.create_table(
        "meeting_intelligence_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["item_id"], ["meeting_intelligence_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["segment_id"], ["transcript_segments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "segment_id", name="uq_meeting_intelligence_evidence"),
    )
    op.create_index(
        op.f("ix_meeting_intelligence_evidence_item_id"), "meeting_intelligence_evidence", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_intelligence_evidence_segment_id"),
        "meeting_intelligence_evidence",
        ["segment_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_meeting_intelligence_evidence_segment_id"), table_name="meeting_intelligence_evidence")
    op.drop_index(op.f("ix_meeting_intelligence_evidence_item_id"), table_name="meeting_intelligence_evidence")
    op.drop_table("meeting_intelligence_evidence")
    op.drop_index("ix_meeting_intelligence_items_run_position", table_name="meeting_intelligence_items")
    op.drop_index(op.f("ix_meeting_intelligence_items_run_id"), table_name="meeting_intelligence_items")
    op.drop_table("meeting_intelligence_items")
    op.drop_index("ix_meeting_intelligence_runs_session_status", table_name="meeting_intelligence_runs")
    op.drop_index(op.f("ix_meeting_intelligence_runs_meeting_session_id"), table_name="meeting_intelligence_runs")
    op.drop_table("meeting_intelligence_runs")
